-- CREATE DATABASE quiz_app;
USE quiz_app;
-- CREATE TABLE users_log(
-- id INT AUTO_INCREMENT PRIMARY KEY,
-- user_name VARCHAR(100) NOT NULL,
-- email VARCHAR(100) UNIQUE NOT NULL,
-- password VARCHAR(100) UNIQUE NOT NULL,
-- created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
-- SELECT * FROM users_log;

-- CREATE TABLE genres (
--     genre_id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(50) UNIQUE NOT NULL
-- );
-- SELECT * FROM genres;

-- WE HAVE TO MAKE RIGHT NOW THE OPTIONS TABLE AND ALSO THE HISTORY TABLE
